In [ ]:
import numpy as np

##Создание матриц

###np.array()

In [ ]:
arr = np.array(list, dtype = None)

**первый аргумент:** итерируемый объект, элементами которого являются другие итерируемые объекты одинаковой длины и содержащие данные одинакового типа.

**второй аргумент** (опциональный): определяет тип данных матрицы. Его можно не задавать, тогда тип данных будет определен из *типа элементов первого аргумента*. При задании этого параметра будет произведена попытка приведения типов.

In [ ]:
a = np.array([1, 2, 3])   # Создаем одномерный массив
print(a)

[1 2 3]


In [ ]:
a = np.array([1, 2, 3])   # Создаем одномерный массив
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)" - кортеж с размерностями
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Изменяем значение элемента массива
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Создаем двухмерный массив
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(np.arange(1, 5)) #Cоздает вектор с эелементами от 1 до 4

matrix = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print ("Матрица:\n", matrix)


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[1 2 3 4]
Матрица:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


###Cпециальные матрицы

In [ ]:
b = np.eye(5)
print ("Единичная матрица:\n", b)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
c = np.ones((7, 5))
print ("Матрица, состоящая из одних единиц:\n", c)

Матрица, состоящая из одних единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
d = np.full((2,2), 7)  # Создает матрицу (1, 2) заполненую заданным значением
print(d)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

e = np.random.random((2,2))
print(e)

[[7 7]
 [7 7]]
[[0.59556536 0.99919934]
 [0.77771767 0.53571464]]


### np.arange()
 создает одномерный массив последовательных чисел из промежутка [start, stop) с заданным шагом step, и метода array.reshape(shape).



In [ ]:
v = np.arange(0, 24, 2)
print ("Вектор-столбец:\n", v)

Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [ ]:
d = v.reshape((3, 4))
print ("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


## Индексирование

In [ ]:
print ("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


###Получаем элемент матрицы:

In [ ]:
print ("Второй элемент третьей строки матрицы:", d[2, 1])

Второй элемент третьей строки матрицы: 18


###array[i, :] или array[:, j] - получение строки/столбца

In [ ]:
print ("Вторая строка матрицы d:\n", d[1, :])
print ("Четвертый столбец матрицы d:\n", d[:, 3])

Вторая строка матрицы d:
 [ 8 10 12 14]
Четвертый столбец матрицы d:
 [ 6 14 22]


###array[list1, list2]

In [ ]:
print ("Элементы матрицы d с координатами (1, 2) и (0, 3):\n", d[[1, 0], [2, 3]])


Элементы матрицы d с координатами (1, 2) и (0, 3):
 [12  6]


### Срезы

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


обратите внимание, что массивы таким образом становятся связаны!

чтобы создать из массивы другой массив и при изменении одного из них второй не менялся, надо изначально создавать второй через **.copy()**!!

In [ ]:
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


###Integer array indexing

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

[[1 2]
 [3 4]
 [5 6]]



In [ ]:
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]


то же самое, но записанное адекватно:

In [ ]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


пример использования

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1]) # Создадим массив индексов
# Выберем из каждой строки элемент с индексом из b (индекс столбца берется из b)
print(a[np.arange(4), b])
print()
# Добавим к этим элементам 10
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print()
print(a[bool_idx])  # Prints "[3 4 5 6]"
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]
[3 4 5 6]


#Векторы, вектор-строки и вектор-столбцы

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

print ("Вектор:\n", a)
print ("Его размерность:\n", a.shape)
print ("Двумерный массив:\n", b)
print ("Его размерность:\n", b.shape)

Вектор:
 [1 2 3]
Его размерность:
 (3,)
Двумерный массив:
 [[1]
 [2]
 [3]]
Его размерность:
 (3, 1)


пример различия:

In [ ]:
a = a.T
b = b.T
print ("Вектор не изменился:\n", a)
print ("Его размерность также не изменилась:\n", a.shape)
print ("Транспонированный двумерный массив:\n", b)
print ("Его размерность изменилась:\n", b.shape)

Вектор не изменился:
 [1 2 3]
Его размерность также не изменилась:
 (3,)
Транспонированный двумерный массив:
 [[1 2 3]]
Его размерность изменилась:
 (1, 3)


##Математические операции

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
arr = np.array([1, 2])

In [ ]:
print(x + y)
print()
print(np.add(x, y))
print('С числом')
print(x + 1)
print('C массивом другой размерности')
print(x + arr)

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]
С числом
[[2. 3.]
 [4. 5.]]
C массивом другой размерности
[[2. 4.]
 [4. 6.]]


In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


## Умножение матриц и столбцов

np.dot(a, b) или a.dot(b)

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)
print ("Матрица A:\n", a)
print ("Матрица B:\n", b)
print ("Результат умножения функцией:\n", r1)
print ("Результат умножения методом:\n", r2)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]


In [ ]:
c = np.array([1, 2])
r3 = b.dot(c)
print ("Матрица:\n", b)
print ("Вектор:\n", c)
print ("Результат умножения:\n", r3)

Матрица:
 [[4 1]
 [2 2]]
Вектор:
 [1 2]
Результат умножения:
 [6 6]


**Обратите внимание**: операция * производит над матрицами покоординатное умножение, а не матричное!

In [ ]:
r = a * b
print ("Матрица A:\n", a)
print ("Матрица B:\n", b)
print ("Результат покоординатного умножения через операцию умножения:\n", r)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат покоординатного умножения через операцию умножения:
 [[4 0]
 [0 2]]


## Объединение массивов

есть горизонтальное, есть верикальное

In [ ]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)
print()


print(np.vstack((a,b)))
print()

print(np.hstack((a,b)))

[[1. 2.]
 [8. 8.]]
[[7. 6.]
 [8. 9.]]

[[1. 2.]
 [8. 8.]
 [7. 6.]
 [8. 9.]]

[[1. 2. 7. 6.]
 [8. 8. 8. 9.]]


In [ ]:
a = np.array(range(10), float)
print(a)
print()

# Превратим в матрицу
a = a.reshape((5, 2))
print(a)
print()

# Вернем обратно
print(a.flatten())

# Другой вариант
print(a.reshape((-1)))
# Превратим в марицу (9, 1)
print(a.reshape((-1, 1)))
# Превратим в марицу (1, 9)
print(a.reshape((1, -1)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [7.]
 [8.]
 [9.]]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


##Транспонирование матриц

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T
print ("Матрица:\n", a)
print ("Транспонирование функцией:\n", b)
print ("Транспонирование методом:\n",  c)

Матрица:
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


##Определитель матрицы

здесь и далее используется модуль [linalg](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#linear-algebra-numpy-linalg)

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)
print ("Матрица:\n", a)
print ("Определитель:\n", det)

Матрица:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Определитель:
 -1.0


## Ранг матрицы

max число линейно независимых строк (столбцов)

In [ ]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
print ("Матрица:\n", a)
print ("Ранг матрицы:", r)

Матрица:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Ранг матрицы: 2


проверим линейную независимость системы векторов

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])
print (np.linalg.matrix_rank(m) == m.shape[0])

True


## СЛАУ

In [ ]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
print ("Матрица A:\n", a)
print ("Вектор b:\n", b)
print ("Решение системы:\n", x)

Матрица A:
 [[3 1]
 [1 2]]
Вектор b:
 [9 8]
Решение системы:
 [2. 3.]


Убедимся, что вектор x действительно является решением системы:



In [ ]:
print (a.dot(x))

Нахождение примерно решения, если точного нет. Для этого мнимизируем ||Ax-b||^2

In [ ]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b, rcond=None)
print ("Матрица A:\n", a)
print ("Вектор b:\n", b)
print ("Псевдорешение системы:\n", x)

Матрица A:
 [[0 1]
 [1 1]
 [2 1]
 [3 1]]
Вектор b:
 [-1.   0.2  0.9  2.1]
Псевдорешение системы:
 [ 1.   -0.95]


##Обращение матриц

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)
print ("Матрица A:\n", a)
print ("Обратная матрица к A:\n", b)
print ("Произведение A на обратную должна быть единичной:\n", a.dot(b))

Матрица A:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Обратная матрица к A:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
Произведение A на обратную должна быть единичной:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##Собственные числа и собственные вектора матрицы

In [ ]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print ("Матрица A:\n", a)
print ("Собственные числа:\n", w)
print ("Собственные векторы:\n", v)

Матрица A:
 [[-1 -6]
 [ 2  6]]
Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


##Расстояние между векторами

l1 - норма

In [ ]:
from numpy.linalg import norm

a = np.array([1, 2, -3])
print('Вектор a:', a)
print('L1 норма вектора a:\n', norm(a, ord=1))


Вектор a: [ 1  2 -3]
L1 норма вектора a:
 6.0


l2-норма

In [ ]:
print ('L2 норма вектора a:\n', norm(a, ord=2))


L2 норма вектора a:
 3.7416573867739413


сами расстояния в этих нормах:

In [ ]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])
print ('Вектор a:', a)
print ('Вектор b:', b)
print ('L1 расстояние между векторами a и b:\n', norm(a - b, ord=1))
print ('L2 расстояние между векторами a и b:\n', norm(a - b, ord=2))

Вектор a: [ 1  2 -3]
Вектор b: [-4  3  8]
L1 расстояние между векторами a и b:
 17.0
L2 расстояние между векторами a и b:
 12.12435565298214


##Скалярное произведение и угол

In [ ]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])
print ('Вектор a:', a)
print ('Вектор b:', b)
cos_angle = np.dot(a, b) / norm(a) / norm(b)
print ('Косинус угла между a и b:', cos_angle)
print ('Сам угол:', np.arccos(cos_angle))

## Комплексные числа

In [ ]:
a = 3 + 2j
b = 1j
print ("Комплексное число a:\n", a)
print ("Комплексное число b:\n", b)

Комплексное число a:
 (3+2j)
Комплексное число b:
 1j


In [ ]:
c = a * a
d = a / (4 - 5j)
print ("Комплексное число c:\n", c)
print ("Комплексное число d:\n", d)

Комплексное число c:
 (5+12j)
Комплексное число d:
 (0.0487804878048781+0.5609756097560976j)
